# Generated by Django 3.1.4 on 2020-12-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_umeop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairitsu',
            field=models.IntegerField(blank=True, default=0, verbose_name='Bairitsu'),
        ),
    ]
