# Generated by Django 3.1.4 on 2020-12-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bairitsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bairitsu',
            field=models.IntegerField(blank=True, default=1, verbose_name='Bairitsu'),
        ),
    ]
