# Generated by Django 3.1.4 on 2021-01-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201231_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stock',
            field=models.IntegerField(blank=True, default=0, verbose_name='Stock'),
        ),
    ]
