# Generated by Django 3.1.4 on 2021-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210129_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='running_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='Running days'),
        ),
    ]
