# Generated by Django 3.1.4 on 2021-01-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_running_days'),
        ('users', '0006_auto_20210125_0010'),
    ]

    operations = [
    ]
