# Generated by Django 3.1.4 on 2021-02-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_running_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_score',
            field=models.IntegerField(blank=True, default=0, verbose_name='Type Score'),
        ),
    ]
