# Generated by Django 3.1.4 on 2021-02-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20210130_0138'),
        ('users', '0008_user_type_score'),
    ]

    operations = [
    ]
