# Generated by Django 3.1.4 on 2020-12-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umeo_site', '0002_umeop_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UmeoP',
        ),
    ]
