# Generated by Django 3.1.4 on 2021-01-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umeo_site', '0005_message_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
